# AUTH
DB_USERNAME = '<DB_ACCESS_USERNAME>'
DB_PASSWORD = '<DB_ACCESS_PASS>'

# CONNECTION
DB_CONN_HOSTNAME = '<HOSTNAME>'
DB_CONN_PORT = '3306'
DB_NAME = 'blog'

BLOG_OWNER_USERNAME = '<Blogs owner username in DB'